- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - railwaycat/emacsmacport
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: zsh, install_options: disable-etcdir }
      - { name: zsh-completions, install_options: disable-etcdir }
      - { name: zsh-syntax-highlighting }
      - { name: zsh-history-substring-search, install_options: disable-etcdir }
      - { name: ansible }
      - { name: coreutils }
      - { name: git }
      - { name: gibo }
      - { name: wget }
      - { name: curl }
      - { name: cmake }
      - { name: autoconf }
      - { name: automake }
      - { name: pkg-config }
      - { name: ctags }
      - { name: tree }
      - { name: lv }
      - { name: nkf }
      - { name: jq }
      - { name: direnv }
      - { name: peco }
      - { name: hub }
      - { name: tig }
      - { name: fish }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: flow }
      - { name: imagemagick }
      - { name: packer }
      - { name: xz }
      - { name: socat }
      - { name: rlwrap }
      - { name: w3m }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: graphviz }
      - { name: autojump }
      - { name: source-highlight }
      - { name: pyenv }
      - { name: go }
      - { name: scala }
      - { name: sbt }
      - { name: ghc }
      - { name: cabal-install }
      - { name: opam }
      - { name: mysql }
      - { name: postgresql }
      - { name: sqlite }
      - { name: redis }
      - { name: vim }
      - { name: emacs-mac }
      - { name: nginx }
      - { name: docker }
      - { name: boot2docker }
    homebrew_cask_packages:
      - { name: java }
      - { name: iterm2 }
      - { name: firefox }
      - { name: opera }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: adobe-reader }
      - { name: skype }
      - { name: hipchat }
      - { name: slack }
      - { name: dash }
      - { name: atom }
      - { name: dropbox }
      - { name: vagrant }
      - { name: virtualbox }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
